#ifndef	_SUREQI_H_
#define	_SUREQI_H_
 
// …Ë÷√ ‰≥ˆŒ¬∂»
extern 	void SuReQiSet(u8 work,u8 Tset);

extern void SuReQiInit(void);

extern BOOL SuReQiRead(u8* canshu );

#endif
/*********************************************************************************************************
**                            End Of File
********************************************************************************************************/
